version: '3.8'

services:
  
  main:
    image: python:3.8-slim
    container_name: sync
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: bash -c "cd app && \
            python3 -m pip install -r requirements.txt && \
            python3 -m flask --app main run --host 0.0.0.0 --port 5000"

  main2:
    image: python:3.8-slim
    container_name: async
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    command: bash -c "cd app && \
            python3 -m pip install -r requirements.txt && \
            python3 -m flask --app main2 run --host 0.0.0.0 --port 5001"