version: '3.8'

services:
  
  main:
    image: python:3.8-alpine
    container_name: sync
    volumes:
      - ./:/app
    command: bin/sh -c 
            "
            cd app &&
            python3 -m pip install -r requirements.txt &&
            python3 -m flask --app main run --port 5000
            "

  main2:
    image: python:3.8-alpine
    container_name: async
    volumes:
      - ./:/app
    command: bin/sh -c 
            "
            cd app &&
            python3 -m pip install -r requirements.txt &&
            python3 -m flask --app main2 run --port 5001
            "